import multer from "multer";
import fs from "fs";
import path from "path";
import util from "util";
import Job from "../models/Job.js";
import asyncHandler from "express-async-handler";

const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, "public/files");
  },
  filename: function (req, file, cb) {
    cb(null, file.originalname);
  },
});

const upload = multer({ storage });

export const updateJobFiles = async (req, res) => {
  try {
    const { jobId } = req.params;

    if (!jobId) {
      return res.status(404).json({ message: "ID not provided" });
    }

    const job = await Job.findById(jobId);

    if (!job) {
      return res.status(404).json({ message: "Job not found" });
    }

    const multerUpload = util.promisify(upload.array("files", 10));

    try {
      await multerUpload(req, res);

      const newFiles = [];

      for (const file of req.files) {
        newFiles.push({
          title: file.originalname,
          fileUrl: file.path, // Use the temporary path generated by multer
        });
      }

      job.files = job.files.concat(newFiles);
      await job.save();

      res.status(200).json({ message: "Job files updated successfully" });
    } catch (error) {
      res.status(500).json({ message: "File upload or save operation failed" });
      console.error(error);
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
    console.error(error);
  }
};

export const downloadJobFile = asyncHandler(async (req, res) => {
  try {
    const { jobId, fileId } = req.params;

    if (!jobId) {
      return res.status(400).json({ message: "Job Id not provided" });
    }

    if (!fileId) {
      return res.status(400).json({ message: "File Id not provided" });
    }

    const job = await Job.findById(jobId);

    if (!job) {
      return res.status(404).json({ message: "Job not found" });
    }

    const file = job.files.id(fileId);

    if (!file) {
      return res.status(404).json({ message: "File not found" });
    }

    const filePath = path.join(__dirname, "..", "public", "files", file.title);

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ message: "File not found on the server" });
    }

    res.download(filePath, file.title, async (error) => {
      if (error) {
        return res.status(500).json({ message: "File download failed" });
      }
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
    console.error(error);
  }
});
